/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include <iomanip>
#include "modes.h"
#include "aes.h"
#include "filters.h"

/* Header for class dev_asmed_encryption_provider_AesProvider */

#ifndef _Included_dev_asmed_encryption_provider_AesProvider
#define _Included_dev_asmed_encryption_provider_AesProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_asmed_encryption_provider_AesProvider
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_asmed_encryption_provider_AesProvider_encrypt
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     dev_asmed_encryption_provider_AesProvider
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_asmed_encryption_provider_AesProvider_decrypt
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
